### ISSUE TITLE
Update Description - "AsyncTask Alternative"

### ISSUE THREAD

**Issue by theelfismike** [fabiendevos/nanotasks#12]
The description is very misleading:

> Extremely light way to execute code in the background on Android. Alternative to AsyncTask.

Yet the whole library is based on AsyncTask:
https://github.com/fabiendevos/nanotasks/blob/master/NanoTasks/nanotasks/src/main/java/com/nanotasks/AbstractTask.java

Perhaps it would be better to describe this as a [facade](http://en.wikipedia.org/wiki/Facade_pattern) for AsyncTasks?

**Comment by fabiendevos** [comment]
You're absolutely right. The description was misleading and I just updated it to describe NanoTask as a wrapper around AsyncTask. I hope this is more accurate.
