### ISSUE TITLE
Min SDK in manifest is higher than necessary

### ISSUE THREAD

**Issue by fabiendevos** [fabiendevos/nanotasks#2]

**Comment by ppamorim** [comment]
+1

**Comment by thebino** [comment]
+1

**Comment by SergioLuis** [comment]
+1

**Comment by dnlbauer** [comment]
+1

**Comment by bafitor** [comment]
+1

**Comment by fabiendevos** [comment]
Thanks you all for voting on this. Thanks to a pull request, master is now backward compatible up to sdk version 9.
I will close this issue as soon a I release a new version to maven central.
I am working on a v2 that should provide a better solution for dealing with the context, and might bring a nicer API, meaning that I would change the API slightly.
Is there anyone using this in a project right now that really need me to publish a v1.1 with current master or can I wait until I'm done and publish directly the v2?

**Comment by ahmadalibaloch** [comment]
Yes we are using. Please do it. Can you do it today or tomorrow?

**Comment by SergioLuis** [comment]
It would be nice from you to release a v1.1, I'm developing something using nanotasks hoping the min API would change, and now that I know it will the v1.1 would make my testing easier.

Thank you.

**Comment by fabiendevos** [comment]
@ahmadalibaloch @SergioLuis and everybody:
I just released the v1.1 to maven central, it should be available soon.
If you are using NanoTaks in a project please create an issue with a link to the project and I'll add it to a list in the readme :)

**Comment by Toolenaar** [comment]
Cheers just been able to download v1.1 and it solved the problem.

**Comment by fabiendevos** [comment]
v1.1 is now available on maven central.
