### ISSUE TITLE
Allow developer to choose task executor

### ISSUE THREAD

**Issue by DagW** [fabiendevos/nanotasks#6]
I like your library, though I miss the ability to choose exector for the asynctask.
For example:

new AsyncTask().executeOnExecutor(AsyncTask. .... )

For choosing wheter to execute in serial or paralell.

Dag

**Comment by fabiendevos** [comment]
It's already possible :)

```
Tasks.executeInBackground(context, backgroundWork, completion, executor);
```

**Comment by DagW** [comment]
Perfect! Missed it :)
